### ISSUE TITLE
Feedback on Tutorial

### ISSUE THREAD

**Issue by wucke13** [au-ts/microkit_tutorial#12]
Hi, I know completed the tutorial and I have some feedback. In general though, it was a great experience!

# Part 1

- [x] Mention stack memory! Currently it is just magically there, and the statement
      > "Well remember that by default a protection domain does not have access to any memory other than its own code."
      seems wrong, surely the TCB allocates for a stack as well? Or is the stack infact built from static memory reserved in the ELF files? Also, how do I change the stack size?
- [x] > "since we in user-space programs we are"
       probably wants to be optimized :)
- [x] > "An interrupt (IRQ)"
       isn't "IRQ" the acronym for "Interrupt Request"?
- [x] > "The channel identifier, an integer from 0 to 62."
      62 is such a random number, care to elaborate (at least via footnote/link) how this comes to be? (I guess it has to do with cap offsets, but knowing would be preferable)
- [x] > "The Microkit library function `void microkit_irq_ack(microkit_channel ch)`, in order to acknowledge the IRQ."
      I spent a couple of hours, because I didn't see the error messages (due too https://github.com/seL4/seL4/issues/1243) which where cause by me acknowledging **every notification**, not only those internally cause by interrupts. Then again, would I have seen the error message sooner, I would have found out quicker. Not sure if more clarification is necessary.

# Part 2

TBC

**Comment by Ivan-Velickovic** [comment]
Thanks for all the feedback. Appreciate it.

> Or is the stack infact built from static memory reserved in the ELF files? Also, how do I change the stack size?

The stack is just a statically sized array in libmicrokit, so can't be changed right now without changing Microkit. However, this will change with https://github.com/seL4/microkit/issues/98 which is planned to be implemented.

> isn't "IRQ" the acronym for "Interrupt Request"?

Yes, but in general I think IRQ is synonymous with interrupts. I can change the tutorial to say "interrupt request" though just to be explicit about it.

> probably wants to be optimized :)

Yep, that's just a bad sentence.

> 62 is such a random number, care to elaborate (at least via footnote/link) how this comes to be? (I guess it has to do with cap offsets, but knowing would be preferable)

It's to do with seL4 badges being 64-bits on 64-bit platforms and the Microkit reserves the first bit for internal use. I will add more detail about the limitation to the Microkit manual and then link to the section from the tutorial for those wondering why it's a random number.

> Then again, would I have seen the error message sooner, I would have found out quicker. Not sure if more clarification is necessary.

I think once the tutorial is using an SDK that has your changes regarding the logging hopefully no one else will run into the same issue.

I will work through each point and let you know when I've update the tutorial.

**Comment by Ivan-Velickovic** [comment]
I've now clarified channel limits more in the manual (https://github.com/seL4/microkit/pull/123) and linked to it from part1 in a footnote.

I'm going to close this since I believe I've addressed everything. But if I haven't or if you have more feedback, please do feel free to make more issues.

Thanks!
